#pragma once

#define MAX_CSHV_VALUE_MOD 256
#define MAX_CSHV_VALUE 255
#define NUM_HIGH_INTENSITY_HEXES 2

#define RAINBOW_STEP 15
#define BACKGROUND_COLOR_CHANGE_MIN 10000
#define BACKGROUND_COLOR_CHANGE_MAX 20000
#define MOVE_CHANGE_MIN 5000
#define MOVE_CHANGE_MAX 8000
#define BACKGROUND_SATURATION 160
#define BACKGROUND_LIGHTNESS 180
#define MAX_MOVE_TARGET_ITERATIONS 1000
#define PEAK_BRIGHTNESS_CENTER_DISTANCE 1
#define LOWEST_BRIGTHENESS_CENTER_DISTANCE 2
#define RAINBOW_STEP 15
#define STATE_CHANGE_TIME 1000
#define ENABLE_FADE_OUT 0

#define MIN_SPLIT_COLOR_DIFF 30

#define MOVE_SAME_BACKGROUND 1
